[package]
name = "whi"
version = "0.7.0"
edition = "2024"
authors = ["Alexander Knott <alexander.knott@posteo.de>"]
description = "Stupid simple PATH management"
repository = "https://github.com/alexykn/whi"
readme = "README.md"
keywords = ["cli", "path", "which", "executable", "unix"]
categories = ["command-line-utilities"]
rust-version = "1.94"
license = "MIT"

[lib]
path = "src/lib.rs"

[[bin]]
name = "whi"
path = "src/bin/whi.rs"

[dependencies]
libc = "1.0.0-alpha.3"
clap = { version = "4.6.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.23.0"
